import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

import { ConnectButton } from "@rainbow-me/rainbowkit";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { mutateAsync: testAddressPublic } =
    api.example.addressTestPublic.useMutation();

  const { mutateAsync: testAddressProtected } =
    api.example.addressTestProtected.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ConnectButton />
        <button
          // eslint-disable-next-line
          onClick={async () => {
            const addr = await testAddressPublic?.();
            console.log("ADDR public", addr);
          }}
        >
          test public
        </button>
        <button
          // eslint-disable-next-line
          onClick={async () => {
            const addr = await testAddressProtected?.();
            console.log("ADDR protected", addr);
          }}
        >
          test protected
        </button>
      </div>
    </>
  );
};

export default Home;
